# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 20:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EndUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('Phone', models.CharField(max_length=11)),
                ('Email', models.EmailField(max_length=100)),
                ('Password', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EventAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Phone', models.CharField(max_length=11)),
                ('Venue', models.CharField(max_length=100)),
                ('StartTime', models.DateTimeField(verbose_name='event start time')),
                ('EndTime', models.DateTimeField(verbose_name='event end time')),
                ('TicketCost', models.DecimalField(decimal_places=2, max_digits=7)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Categories')),
                ('User', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=50)),
                ('Zip', models.CharField(max_length=5)),
                ('Country', models.CharField(max_length=50)),
                ('MaxCapacity', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='enduser',
            name='Event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.EventAdmin'),
        ),
    ]
